### ISSUE TITLE
Install uniforms into template storybook

### ISSUE THREAD

**Issue by zeroasterisk** [zeroasterisk/react-uniforms-widgets#11]
The template should not depend on `uniforms`, but it can require it as a peer.

But the template **should** use `uniforms` for `react-storybook`, as a first step towards a reasonable preview for uniforms, and then our widgets.

Uniforms will not work without a schema.  It supports `SimpleSchema2`, and we could bridge other schemas (there are other tasks for that)... so, for now, minimum work will probably be `SimpleSchema2`

**Comment by errinjohnson** [comment]
https://www.npmjs.com/package/react-uniform   -  I installed the react-uniform on my local computer. 
Do we import the react-uniform to the storybook template config file.  Newbie with react.

**Comment by zeroasterisk** [comment]
Yes, in this case, storybook is basically our app/page. So see if you can make it load uniforms. Likely to get errors along the way. That's normal.  Make a branch. make whatever progress you can, commit stuff at points that make sense. Make a pull request, even if incomplete, and we can discuss on the PR... (Standing PRs are common, letting people collaborate on evolving sets of changes)
