### ISSUE TITLE
Hacktoberfest Invite - front end / React / Uniforms - Great for noobs!

### ISSUE THREAD

**Issue by zeroasterisk** [zeroasterisk/react-uniforms-widgets#9]
See some of the other issues and roadmap on this project.

This is a seed project for new developers who need a "safe" and easy opening into collaborating on open source....

Even the README and other documentation - try it out... make a fork, make a PR, and help if you can.

**Comment by TinaBryan** [comment]
[@errinjohnson](https://github.com/errinjohnson)

**Comment by TinaBryan** [comment]
[@perfectloser](https://github.com/perfectloser)

**Comment by TinaBryan** [comment]
[@syoustra](https://github.com/syoustra)

**Comment by TinaBryan** [comment]
Hello Leslie Heinzen,
Let's do this thing!
[@Zero-man](https://github.com/Zero-man)
